-- Delivery subsystem, dispatch-side data model (Prompt 7). Fare formula
-- (Prompt 8) and the rider-facing board (Prompt 9) are explicitly out of
-- scope here — see ITRED_GOVERNANCE_AND_ARCHITECTURE.md's "Open items":
-- distance threshold, confirmation code format, load-size tiers, and
-- ride-type categories were all pending proposal-and-sign-off before this
-- migration; the values below reflect the confirmed decisions:
--   * local vs. intercity boundary: 10km (computed and stored by the
--     server at dispatch-creation time, not recomputed here)
--   * confirmation code: 6-character alphanumeric (unambiguous charset,
--     generated by server/lib/deliveryCode.ts)
--   * load-size tiers: small / medium / large
--   * ride types: bicycle / motorbike / car / van
--
-- DL-008's "never queue delivery dispatch in the outbox" requirement means
-- this table is deliberately NOT written via the transactional-outbox path
-- (server/sync/outboxWriter.ts) — the Express backend writes directly to
-- this table (service-role client) synchronously at creation time, only
-- once its own connectivity probe reports ONLINE, and mirrors the row into
-- local SQLite afterwards. See server/routes/deliveryOrders.ts.

-- --------------------------------------------------------
-- ENUMS
-- --------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'delivery_order_status') then
    create type delivery_order_status as enum (
      'posted', 'accepted', 'in_transit', 'delivered', 'failed', 'under_investigation', 'cancelled'
    );
  end if;
  if not exists (select 1 from pg_type where typname = 'delivery_route_class') then
    create type delivery_route_class as enum ('local', 'intercity');
  end if;
  if not exists (select 1 from pg_type where typname = 'delivery_load_size') then
    create type delivery_load_size as enum ('small', 'medium', 'large');
  end if;
  if not exists (select 1 from pg_type where typname = 'delivery_ride_type') then
    create type delivery_ride_type as enum ('bicycle', 'motorbike', 'car', 'van');
  end if;
  if not exists (select 1 from pg_type where typname = 'rider_status') then
    create type rider_status as enum ('ACTIVE', 'OFF_DUTY', 'SUSPENDED');
  end if;
end $$;

-- --------------------------------------------------------
-- RIDERS — the business's own employed/contracted riders, not a
-- third-party marketplace. Tenant-scoped, one rider profile per underlying
-- staff row (the staff row already carries access_role = 'rider' and the
-- shared PIN credential per DL-005/DL-011).
-- --------------------------------------------------------
create table if not exists riders (
  id text not null,
  tenant_id text not null references tenants(id) on delete cascade,
  staff_id text not null,
  vehicle_type delivery_ride_type not null,
  phone text,
  status rider_status not null default 'ACTIVE',
  home_branch_id text references branches(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, id),
  unique (tenant_id, staff_id),
  foreign key (tenant_id, staff_id) references staff(tenant_id, id) on delete cascade
);
create index if not exists idx_riders_tenant on riders(tenant_id);

create trigger trg_riders_updated_at before update on riders
  for each row execute function set_updated_at();

alter table riders enable row level security;

create policy riders_select on riders for select
  using (tenant_id = app_current_tenant_id() or app_is_super_admin());
create policy riders_write on riders for insert
  with check (tenant_id = app_current_tenant_id() and app_is_back_office_role());
create policy riders_update on riders for update
  using (tenant_id = app_current_tenant_id() and app_is_back_office_role())
  with check (tenant_id = app_current_tenant_id());

-- --------------------------------------------------------
-- DELIVERY ORDERS
-- --------------------------------------------------------
create table if not exists delivery_orders (
  id text not null,
  tenant_id text not null references tenants(id) on delete cascade,
  sale_id text not null,
  sale_number text not null,

  pickup_branch_id text references branches(id) on delete set null,
  pickup_branch_name text,
  -- Branches have no persisted geocoded record yet (see governance doc's
  -- "Second Tauri flag" note — branches aren't a real backend entity in
  -- this codebase today), so pickup coordinates are captured redundantly
  -- here at dispatch time, exactly as pickup_branch_name already is.
  pickup_latitude numeric(9, 6) not null,
  pickup_longitude numeric(9, 6) not null,

  delivery_address_line text not null,
  delivery_city text,
  delivery_landmark text,
  delivery_latitude numeric(9, 6) not null,
  delivery_longitude numeric(9, 6) not null,
  delivery_contact_name text,
  delivery_contact_phone text,

  load_size_tier delivery_load_size not null,
  ride_type_requirement delivery_ride_type not null,

  distance_km numeric(8, 3) not null,
  route_class delivery_route_class not null,

  -- Fare formula is Prompt 8's job — left null here by design.
  fare_amount numeric(18, 4),

  status delivery_order_status not null default 'posted',

  confirmation_code text not null,
  confirmation_code_expires_at timestamptz not null,
  confirmation_code_attempt_count integer not null default 0,

  rider_id text references riders(id) on delete set null,

  created_by_staff_id text,
  created_by_staff_name text,
  origin_terminal_id text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  primary key (tenant_id, id),
  foreign key (tenant_id, sale_id) references sales_transactions(tenant_id, sale_id) on delete restrict
);
create index if not exists idx_delivery_orders_tenant on delivery_orders(tenant_id);
create index if not exists idx_delivery_orders_sale on delivery_orders(tenant_id, sale_id);
create index if not exists idx_delivery_orders_status on delivery_orders(tenant_id, status);
create index if not exists idx_delivery_orders_rider on delivery_orders(rider_id);

create trigger trg_delivery_orders_updated_at before update on delivery_orders
  for each row execute function set_updated_at();

alter table delivery_orders enable row level security;

-- till_operator sessions only see their own branch's dispatches; head
-- office/executive/platform-admin see the whole tenant — same shape as
-- sales_transactions_select.
create policy delivery_orders_select on delivery_orders for select
  using (
    tenant_id = app_current_tenant_id()
    and (not app_is_branch_scoped_role() or pickup_branch_id = app_current_branch_id())
    or app_is_super_admin()
  );

-- Creation is a till/head-office action (never executive, which is
-- read-only per DL-002, and never rider — a rider accepts/updates an
-- existing dispatch, Prompt 9's job, not this one).
create policy delivery_orders_insert on delivery_orders for insert
  with check (
    tenant_id = app_current_tenant_id()
    and (not app_is_branch_scoped_role() or pickup_branch_id = app_current_branch_id())
    and app_current_role() in ('till_operator', 'head_office_staff', 'platform_super_admin')
  );

-- No UPDATE policy defined yet: status transitions (accept/in_transit/
-- delivered/failed/under_investigation/cancelled) and confirmation-code
-- attempt tracking are Prompt 9's (rider board) job to design and gate —
-- deliberately not guessed at here.
